### PR TITLE
Fix error reporting on 2.11

### LINKED ISSUE #1161: Fix Diagnostics reporter exit codes
To clarify important bits regarding this change:
- this fixes broken 2.11 support - I think it's important to get this fixed ASAP
- to do it properly, diagnostics reporter should be fixed also when it is enabled for all supported versions of Scala. This means we need to have failing test scenarios for all major Scala versions for error reporting. Unfortunately I have no time to look into it myself. Any chances @andrefmrocha you can look into it?

_Originally posted by @liucijus in https://github.com/bazelbuild/rules_scala/issues/1159#issuecomment-738802911_

With #1159 , whenever the diagnostic reporter flag is turned off, it is assured that the exit code is correct. However, when the `ProtoReporter` is used, the exit code is not properly outputted. This should be addressed and several test cases for this should be created.

### PR DESCRIPTION
**Pull request by andrefmrocha**
### Description
Closes #1161 . Changed how the reporter is obtained from the `MainClass`, since the call to `getDeclaredField` is obtaining the wrong reporter for scala 2.11.

### Motivation
Fixes problems regarding building for scala 2.11, where the build was exiting without flagging errors, whenever the `DiagnosticsReporter` was used

### CODE REVIEW

File: src/java/io/bazel/rulesscala/scalac/ScalacWorker.java [hunk 1]
```diff
@@ -21,17 +20,6 @@
 class ScalacWorker implements Worker.Interface {
   private static boolean isWindows = System.getProperty("os.name").toLowerCase().contains("windows");
 
-  /** This is the reporter field for scalac, which we want to access */
-  private static Field reporterField;
-
-  static {
-    try {
-      reporterField = Driver.class.getDeclaredField("reporter"); // NoSuchFieldException
```
Comment (andrefmrocha) [inline src/java/io/bazel/rulesscala/scalac/ScalacWorker.java:29]: This field could be maintained to get access to the `ReportableMainClass` implementation on our side, but I do think this would be unnecessary added complexity.

**Comment by andrefmrocha** [comment]
@liucijus I'm keeping this PR as draft until we close #1176 . Do let me know what you think though!

**Comment by liucijus** [comment]
@andrefmrocha #1176 is merged. Let's proceed with this one?

**Comment by andrefmrocha** [comment]
> @andrefmrocha #1176 is merged. Let's proceed with this one?

Should be gtg? Let me know what you think

File: test_version.sh [hunk 2]
```diff
@@ -157,7 +157,6 @@ TEST_TIMEOUT=15 $runner test_reporter "${scala_2_11_version}" "${no_diagnostics_
 TEST_TIMEOUT=15 $runner test_reporter "${scala_2_12_version}" "${no_diagnostics_reporter_toolchain}"
 TEST_TIMEOUT=15 $runner test_reporter "${scala_2_13_version}" "${no_diagnostics_reporter_toolchain}"
 
-#TODO: Uncomment this out after diagnostics reporter properly reports errors for scala 2.11
-#TEST_TIMEOUT=15 $runner test_reporter "${scala_2_11_version}" "${diagnostics_reporter_toolchain}"
+TEST_TIMEOUT=15 $runner test_reporter "${scala_2_11_version}" "${diagnostics_reporter_toolchain}"
 TEST_TIMEOUT=15 $runner test_reporter "${scala_2_12_version}" "${diagnostics_reporter_toolchain}"
 TESTs_TIMEOUT=15 $runner test_reporter "${scala_2_13_version}" "${diagnostics_reporter_toolchain}"
```
Comment (liucijus) [inline test_version.sh:162]: `TESTs_TIMEOUT` -> `TEST_TIMEOUT`

**Comment by liucijus** [comment]
@andrefmrocha can you fix https://github.com/bazelbuild/rules_scala/pull/1177#discussion_r556794908 from previous PR and we can merge this one

File: test_version.sh (hunk 2 above)
Comment (andrefmrocha) [reply test_version.sh]: Done!

**Comment by andrefmrocha** [comment]
> @andrefmrocha can you fix [#1177 (comment)](https://github.com/bazelbuild/rules_scala/pull/1177#discussion_r556794908) from previous PR and we can merge this one

Was precisely doing it right now :smile: !

**Review by liucijus — APPROVED** [review]

**Review by ittaiz — APPROVED** [review]
